name: 'Daily Inspirational Quote'
description: 'Send a daily inspirational quote to your email or workflow using GitHub Actions.'
author: 'ijay'
inputs:
  recipient:
    description: 'Where to send the quote (e.g., email)'
    required: false
    default: 'GitHub Actions log'
outputs:
  quote:
    description: 'The inspirational quote that was sent'
  author:
    description: 'The author of the inspirational quote'
runs:
  using: 'composite'
  steps:
    - name: Fetch inspirational quote
      id: get_quote
      shell: bash
      run: |
        response=$(curl -s https://zenquotes.io/api/random)
        quote=$(echo "$response" | jq -r '.[0].q')
        author=$(echo "$response" | jq -r '.[0].a')
        echo "QUOTE=$quote" >> $GITHUB_ENV
        echo "AUTHOR=$author" >> $GITHUB_ENV
        echo "::set-output name=quote::$quote"
        echo "::set-output name=author::$author"
    - name: Send email with quote
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Your Daily Inspirational Quote 🌟"
        to: ${{ secrets.TO_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          "${{ env.QUOTE }}"
          — ${{ env.AUTHOR }}

          Sent automatically by GitHub Action. Built with 💖 by Ijay.
        secure: true
branding:
  icon: 'light-bulb'
  color: 'yellow'
