name: Daily Inspirational Quote

on:
  workflow_call:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  send-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure jq is installed
        run: sudo apt-get install -y jq

      - name: Fetch inspirational quote
        id: get_quote
        run: |
          set -e
          response=$(curl -s https://zenquotes.io/api/random)
          quote=$(echo "$response" | jq -r '.[0].q')
          author=$(echo "$response" | jq -r '.[0].a')
          echo "QUOTE=$quote" >> $GITHUB_ENV
          echo "AUTHOR=$author" >> $GITHUB_ENV

      - name: Send email with quote
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Your Daily Inspirational Quote 🌟"
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            ${{ env.QUOTE }}
            — ${{ env.AUTHOR }}

            Sent automatically by GitHub Action. Built with 💖 by Ijay.
          secure: true
