name: Daily Inspirational Quote

on:
  schedule:
    - cron: '0 8 * * *'   # Runs every day at 8:00 AM UTC (change this time if you want)
  workflow_dispatch:       # Allows you to run the workflow manually from the Actions tab

jobs:
  send-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch inspirational quote
        id: get_quote
        run: |
          response=$(curl -s https://zenquotes.io/api/random)
          quote=$(echo "$response" | jq -r '.[0].q')
          author=$(echo "$response" | jq -r '.[0].a')
          echo "QUOTE=$quote" >> $GITHUB_ENV
          echo "AUTHOR=$author" >> $GITHUB_ENV

      - name: Send email with quote
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Your Daily Inspirational Quote 🌟"
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            "${{ env.QUOTE }}"
            — ${{ env.AUTHOR }}

            Sent automatically by your GitHub Action 🚀
          secure: true
